### ISSUE TITLE
Missing image in Chapter 4

### ISSUE THREAD

**Issue by Ion-Drive** [Apress/advanced-applied-deep-learning#1]
Hello,

Great book ... been absorbing the info as quickly as I can!

I did notice that "elephant.jpg" from Chapter 4 (as referred to on page 143) seems to be missing from the github repo.

Or at least, I have not been able to find it.

Cheers,
Ion-Drive

**Comment by michelucci** [comment]
Thanks a lot. I added the image in the folder. Happy you enjoy the book.
Best, Umberto
