### ISSUE TITLE
Folders Missing

### ISSUE THREAD

**Issue by malraharsh** [Apress/advanced-applied-deep-learning#3]
In Chapter 4 - Transfer Learning

These data folders are missing -
1.train
2.validation_data

Thus causing error in whole code

**Comment by michelucci** [comment]
The folders have been added in the Chapter 4 folder. Thanks for pointing that out.
Best, Umberto

**Comment by malraharsh** [comment]
Most welcome and thank you sir, I have been enjoying your book lately. Written with great explanation.
